  variable subnet_name {}
  variable custom_metadata  {}
  variable zones     {}
  variable nginx-plus-cluster-size   {}
  variable consul_server_cluster_name  {}
  variable machine_type    {}
  variable "network" {}
  variable "random_id" {}
  variable "f1_api_image" {}
  variable "vpc_name" {}
  variable "metadata_key_name_for_cluster_size" {}
  variable "consul_client_cluster_size" {}
  variable "region_name" {}
  variable "f1-pi-cluster-size" {}
  variable "hello_nginx_api_image" {}
  variable "hello-nginx_-pi-cluster-size" {}
  variable "weather_api_image" {}
  variable "weather-api-cluster-size" {}
