  variable subnet_name {}
  variable custom_metadata  {}
  variable zones     {}
  variable nginx-plus-cluster-size   {}
  variable consul_server_cluster_name  {}
  variable machine_type    {}
  variable "network" {}
  variable "random_id" {}
  variable "nginx-plus-image-name" {}
  variable "vpc_name" {}
  variable "metadata_key_name_for_cluster_size" {}
  variable "consul_client_cluster_size" {}
  variable "region_name" {}
  variable health_check_path {}
  variable health_check_port {}
  variable health_check_interval {}
  variable health_check_healthy_threshold {} 
  variable health_check_unhealthy_threshold {}
  variable health_check_timeout {}
  variable protocol {}

